### PR TITLE
Add icons

### LINKED ISSUE #1: Add an app icon

### PR DESCRIPTION
**Pull request by hanaral**
Fixes #1

### CODE REVIEW

**Comment by ryonakano** [comment]
@hanaral Thank you for your pull request, looks good! Would you mind creating icons for 16, 24, 48, and 128px too?

**Comment by ryonakano** [comment]
Screenshot from 2021-02-22 09-53-31

FYI this is how the icon looks like on the desktop

**Comment by hanaral** [comment]
AFAIK the icon name is supposed to by the reverse DNS name, so it would be `com.github.ryonakano.louper` in each of the px folders

**Comment by ryonakano** [comment]
Any chance you create icons for 24 and 48 px?

**Comment by hanaral** [comment]
ごめんね。
先週大学為に色んな資料を準備したから忙しかった。
I'll get a few of them done today！

**Review by ryonakano — APPROVED** [review]
Thank you for your hard work on this!! 本当にかわいいアイコンです！ :heart_eyes:

**Pull request merged**
