### PR TITLE
Add Flatpak manifest

### PR DESCRIPTION
**Pull request by ryonakano**
@hanaral Sorry to bother you, but I'm struggling in *flatpaking* this app; building and installation succeed but the app doesn't launch…do you possibly know how can I fix it?

### CODE REVIEW

**Comment by hanaral** [comment]
Without even testing, just by knowing how little dependencies this app has I'd assume it has something to do with accessing the clipboard. (I just tested, it fails silently 😭️)
@hezral how did you manage to make the clipboard thingy work in Clips?

**Comment by hezral** [comment]
this part seems unable to get the values from the Gdk.Monitor class i think. 
If i changed it to fixed values, it worked. haven't tested on why its not able to get the values though. 
i did try to see what it prints out as, and didn't get anything. 

    public MainWindow () {
        Object (
            resizable: false,
            default_width: primary_monitor_workarea.width / 2,
            default_height: primary_monitor_workarea.height / 4
        );
    }

also, i commented out settings part since it was giving this error, might want to look at the elementary first party apps on how its doing these settings in flatpak:
```
** (com.github.ryonakano.louper:2): CRITICAL **: 08:53:51.218: Settings.vala:87: Could not connect: No such file or directory
** (com.github.ryonakano.louper:2): CRITICAL **: 08:53:51.218: Settings.vala:109: Could not connect: No such file or directory
```

        var granite_settings = Granite.Settings.get_default ();
        var gtk_settings = Gtk.Settings.get_default ();

        gtk_settings.gtk_application_prefer_dark_theme = granite_settings.prefers_color_scheme == Granite.Settings.ColorScheme.DARK;

        granite_settings.notify["prefers-color-scheme"].connect (() => {
            gtk_settings.gtk_application_prefer_dark_theme = granite_settings.prefers_color_scheme == Granite.Settings.ColorScheme.DARK;
        });

and here's the manifest i used, nothing special needed :)

```
app-id: com.github.ryonakano.louper
runtime: io.elementary.Platform
runtime-version: 'daily'
sdk: io.elementary.Sdk
command: com.github.ryonakano.louper
appstream-compose: false
finish-args:
  - --socket=wayland
  - --socket=fallback-x11
  - --share=network
  - --device=dri
modules:
  - name: louper
    buildsystem: meson
    sources:
      - type: dir
        path: .
```

**Comment by ryonakano** [comment]
Hi @hanaral and @hezral, thank you very much for both of your help!! :tada:

I confirmed that commenting out some lines as @hezral mentioned launches the app as expected. And I came up with an solution to fix this problem inspired from this fix: #8.

**Comment by ryonakano** [comment]
OK, I merged #8 and now this branch should launch the app as expected. One thing I concern is the following error messages on launch:

```
** (com.github.ryonakano.louper:2): WARNING **: 21:12:29.382: CustomShortcutSettings.vala:46: Schema "org.gnome.settings-daemon.plugins.media-keys" is not installed on your system.

** (com.github.ryonakano.louper:2): CRITICAL **: 21:12:29.382: custom_shortcut_settings_list_custom_shortcuts: assertion 'available' failed

** (com.github.ryonakano.louper:2): CRITICAL **: 21:12:29.382: custom_shortcut_settings_create_shortcut: assertion 'available' failed
```

Now the app is sandboxed, so it can't access to the host dconf settings. Is there any solution to access to it or shouldn't it be accessed in Flatpak world?

**Comment by ryonakano** [comment]
@hanaral @hezral Could you guys confirm this works as expected now?

**Comment by hezral** [comment]
Cool, confirmed that it works now :) and this is a brilliant idea for an app btw

**Comment by hanaral** [comment]
@ryonakano Yeah it works now _as expected_:
Screenshot from 2021-05-20 17 37 12

**Comment by ryonakano** [comment]
Thank you for both of you guys! ☺️
BTW @hanaral I was almost forgotten that I need to fix #6 that you reported…I just recalled it seeing your screenshot above 😅 Will take a look soon before the app gets on AppCenter!

**Comment by hanaral** [comment]
@ryonakano 問題無い！

**Pull request merged**
